# Generated by Django 5.2.7 on 2025-10-14 15:04

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-()\\s]+$', 'Invalid phone number format')])),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
