# Generated by Django 5.0.14 on 2025-11-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_phoneverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
