# Generated by Django 5.0.14 on 2026-01-28 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phoneverification_alter_customuser_mobile_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='phoneverification',
            name='verified_at',
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
