# Generated by Django 5.0.14 on 2026-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('comment', 'Comment'), ('payment', 'Payment'), ('system', 'System')], max_length=20),
        ),
    ]
