# admin_features/serializers.py
from rest_framework import serializers
from articles.models import Article, Category
from comments.models import Comment

class AdminCategorySerializer(serializers.ModelSerializer):
    """
    Admin-facing serializer for Category.
    Slug remains read-only because slug is auto-generated by the model on save.
    """
    class Meta:
        model = Category
        fields = ["id", "name", "slug"]
        read_only_fields = ["slug"]


class AdminArticleSerializer(serializers.ModelSerializer):
    """
    Admin serializer that allows full CRUD from admin API.
    - Writable fields include: title, slug, excerpt, body, image, is_approved,
      is_slider, popularity, categories (via category_ids).
    - Keeps permalink and comment_count as read-only.
    """
    categories = AdminCategorySerializer(many=True, read_only=True)
    category_ids = serializers.PrimaryKeyRelatedField(
        many=True, write_only=True, queryset=Category.objects.all(), source="categories"
    )
    permalink = serializers.ReadOnlyField()
    comment_count = serializers.SerializerMethodField(read_only=True)
    author_username = serializers.CharField(source="author.username", read_only=True)

    class Meta:
        model = Article
        fields = [
            "id",
            "title",
            "slug",
            "excerpt",
            "body",
            "image",
            "categories",
            "category_ids",
            "author",
            "author_username",
            "is_approved",
            "is_slider",
            "popularity",
            "permalink",
            "comment_count",
            "created_at",
            "updated_at",
        ]
        # Admin needs to be able to edit slug, is_approved, popularity, etc.
        read_only_fields = ["permalink", "comment_count", "created_at", "updated_at", "author_username"]

    def get_comment_count(self, obj):
        # Count approved comments
        return obj.comments.filter(approved=True).count()

    def validate_image(self, image):
        # Mirror existing image size validation if image field used
        MAX_IMAGE_SIZE_BYTES = 2 * 1024 * 1024  # 2MB
        if not image:
            return image
        if getattr(image, "size", None) and image.size > MAX_IMAGE_SIZE_BYTES:
            raise serializers.ValidationError("Image size must be <= 2MB.")
        return image

    def create(self, validated_data):
        categories = validated_data.pop("categories", [])
        article = Article.objects.create(**validated_data)
        if categories:
            article.categories.set(categories)
        return article

    def update(self, instance, validated_data):
        categories = validated_data.pop("categories", None)
        for attr, value in validated_data.items():
            setattr(instance, attr, value)
        if categories is not None:
            instance.categories.set(categories)
        instance.save()
        return instance
