# Generated by Django 5.0.14 on 2025-11-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesetting',
            options={'verbose_name': 'Theme Setting', 'verbose_name_plural': 'Theme Settings'},
        ),
    ]
